[server]
runOnSave = true
headless = true
enableCORS = true
enableXsrfProtection = true
port = 8501

[browser]
gatherUsageStats = true

[theme]
base="dark"
primaryColor="#003366"
backgroundColor="#1e1e1e"
secondaryBackgroundColor="#2c2c2c"
textColor="#ffffff"
font="sans serif"

[general]
# Valeur par défaut, pas besoin de la forcer
# showWarningOnDirectExecution = true

# Menu par défaut de Streamlit
# Si tu veux garder ton menu personnalisé, tu peux remettre [menuItems]
