[server]
runOnSave = true
headless = true
enableCORS = true
enableXsrfProtection = true
port = 8501

[browser]
gatherUsageStats = true

[theme]
base = "dark"
primaryColor = "#003366"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#2c2c2c"
textColor = "#ffffff"
font = "sans serif"

[client]
# Désactive la navigation automatique du dossier pages
showSidebarNavigation = false

[toolbar]
# Cache les options avancées (menu hamburger)
mode = "minimal"   