[server]
runOnSave = true
headless = true
enableCORS = true
enableXsrfProtection = true
port = 8501

[browser]
gatherUsageStats = true



[client]
# Désactive la navigation automatique du dossier pages
showSidebarNavigation = false

[toolbar]
# Cache les options avancées (menu hamburger)
mode = "minimal"   